---
kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/presslabs/wordpress-operator

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: install dependencies
  pull: always
  image: quay.io/presslabs/bfc:0.11
  commands:
  - make -j4 build.tools

- name: verify generated code
  image: quay.io/presslabs/bfc:0.11
  commands:
  - make generate
  - git diff --exit-code

- name: lint
  image: quay.io/presslabs/bfc:0.11
  commands:
  - make -j4 lint

- name: test
  image: quay.io/presslabs/bfc:0.11
  commands:
  - make test

- name: build
  image: quay.io/presslabs/bfc:0.11
  commands:
  - make -j4 build

- name: publish
  image: quay.io/presslabs/bfc:0.11
  environment:
    DOCKER_REGISTRY: quay.io
    DOCKER_USERNAME: presslabs+drone
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN
  commands:
  - /usr/local/bin/setup-credentials-helper.sh
  - make publish
  when:
    event:
      - push
      - tag

services:
- name: docker
  image: docker:dind
  privileged: true
  commands:
    - /usr/local/bin/dockerd-entrypoint.sh dockerd --host "unix:///workspace/docker.sock" --storage-driver overlay2 --log-level error

trigger:
  ref:
    - refs/pull/**
    - refs/heads/master
    - refs/heads/release-*
    - refs/tags/**
