run:
  skip-files:
    - zz_generated

linters-settings:
  dupl:
    threshold: 400
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: true
  lll:
    line-length: 170
    tab-width: 4

linters:
  presets:
    - bugs
    - unused
    - format
    - style
    - complexity
    - performance

  disable:
    - gochecknoglobals
    - goimports
    - gochecknoinits
    - wsl

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    # gosec G104, about unhandled errors. We do that with errcheck already
    - "G104: Errors unhandled"
    - "mnd: "
    - "Line contains TODO/BUG/FIXME"
  exclude-rules:
    - linters:
        - godox
      text: "TODO:"
    - linters:
      # Ignore package comments (ST1000) since most of the time are irrelevant
      - stylecheck
      text: "ST1000"
