run:
  skip-files:
    - zz_generated

linters-settings:
  dupl:
    threshold: 400
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: true
  lll:
    line-length: 170
    tab-width: 4

linters:
  presets:
    - bugs
    - unused
    - format
    - style
    - complexity
    - performance

  # we should re-enable them and make lint pass
  disable:
    - goimports
    - maligned
    - wsl
    - gomnd
    - gochecknoglobals
    - gochecknoinits

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    # gosec G104, about unhandled errors. We do that with errcheck already
    - "G104: Errors unhandled"
    # TODO: reenable
    - "ST1000: at least one file in a package should have a package comment"
    # Allow TODOs
    - "Line contains TODO/BUG/FIXME"
