/*
Copyright 2018 Pressinfra SRL

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/presslabs/wordpress-operator/pkg/apis/wordpress/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWordpresses implements WordpressInterface
type FakeWordpresses struct {
	Fake *FakeWordpressV1alpha1
	ns   string
}

var wordpressesResource = schema.GroupVersionResource{Group: "wordpress.presslabs.org", Version: "v1alpha1", Resource: "wordpresses"}

var wordpressesKind = schema.GroupVersionKind{Group: "wordpress.presslabs.org", Version: "v1alpha1", Kind: "Wordpress"}

// Get takes name of the wordpress, and returns the corresponding wordpress object, and an error if there is any.
func (c *FakeWordpresses) Get(name string, options v1.GetOptions) (result *v1alpha1.Wordpress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(wordpressesResource, c.ns, name), &v1alpha1.Wordpress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wordpress), err
}

// List takes label and field selectors, and returns the list of Wordpresses that match those selectors.
func (c *FakeWordpresses) List(opts v1.ListOptions) (result *v1alpha1.WordpressList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(wordpressesResource, wordpressesKind, c.ns, opts), &v1alpha1.WordpressList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WordpressList{}
	for _, item := range obj.(*v1alpha1.WordpressList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested wordpresses.
func (c *FakeWordpresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(wordpressesResource, c.ns, opts))

}

// Create takes the representation of a wordpress and creates it.  Returns the server's representation of the wordpress, and an error, if there is any.
func (c *FakeWordpresses) Create(wordpress *v1alpha1.Wordpress) (result *v1alpha1.Wordpress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(wordpressesResource, c.ns, wordpress), &v1alpha1.Wordpress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wordpress), err
}

// Update takes the representation of a wordpress and updates it. Returns the server's representation of the wordpress, and an error, if there is any.
func (c *FakeWordpresses) Update(wordpress *v1alpha1.Wordpress) (result *v1alpha1.Wordpress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(wordpressesResource, c.ns, wordpress), &v1alpha1.Wordpress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wordpress), err
}

// Delete takes name of the wordpress and deletes it. Returns an error if one occurs.
func (c *FakeWordpresses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(wordpressesResource, c.ns, name), &v1alpha1.Wordpress{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWordpresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(wordpressesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.WordpressList{})
	return err
}

// Patch applies the patch and returns the patched wordpress.
func (c *FakeWordpresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Wordpress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(wordpressesResource, c.ns, name, data, subresources...), &v1alpha1.Wordpress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wordpress), err
}
