- op: remove
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/sidecars/items/properties/ports

- op: remove
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/initContainers/items/properties/ports
