- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/sidecars/items/properties/ports

- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/initContainers/items/properties/ports
